server:
  port: 10001
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.115.209.12:3306/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
