spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=uri,baidu

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=uri,qq

        - id: route_thirdpart
          uri: lb://thirdpart
          predicates:
            - Path=/api/thirdpart/**
          filters:
            - RewritePath=/api/thirdpart/(?<segment>.*),/thirdpart/$\{segment}

        - id: route_coupon
          uri: lb://coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/coupon/(?<segment>.*),/coupon/$\{segment}

        - id: route_member
          uri: lb://member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/member/(?<segment>.*),/member/$\{segment}

        - id: route_product
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>.*),/product/$\{segment}

        - id: route_renren
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gateway
server:
  port: 88
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

